# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "gomoku.xcodeproj")
    build_app(workspace: "gomoku.xcworkspace", scheme: "gomoku")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    increment_build_number(xcodeproj: "gomoku.xcodeproj")
    build_app(workspace: "gomoku.xcworkspace", scheme: "gomoku")
    pilot(
        skip_waiting_for_build_processing: true
    )
    upload_to_testflight
    clean_build_artifacts
    commit_version_bump(
        message: "Fastlane iOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
        xcodeproj: "./gomoku.xcodeproj",
        force: true
    )
  end
end
